name: geospatial-environment

dependencies:
- geopandas>=0.9.0
- geoplot>=0.4.4
- pint>=0.11
- matplotlib=3.5.1
- pandas=1.4.1
- numpy=1.22.2
- shapely=1.8.0
- networkx=2.6.3
- plotly>=4.14.3
- folium>=0.12.1.post1
- openpyxl=3.0.9
- pygraphviz=1.9
- xarray=0.20.1
- dask=2022.02.1
- netCDF4=1.5.8
- bottleneck=1.3.4
- rioxarray=0.11.1
- cartopy=0.20.2
- ipykernel=6.15.0
- plotly=5.9.0
- regionmask
- pygeos
- pip
- pip:
  - graphviz==0.20
  - basemap==1.3.3
  - pandas_datareader==0.10.0
  - jupyter
  - lxml